name: store-api

services:

  db:
    image: postgres:17.6
    hostname: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # ports:
    #   - 5432:5432
    volumes:
      - ./volume/db:/var/lib/postgresql/data

  account:
    build:
      context: ./pma252.account-service
      dockerfile: Dockerfile
    hostname: account
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    deploy:
      replicas: 1
    depends_on:
      - db

  auth:
    build:
      context: ./pma252.auth-service
      dockerfile: Dockerfile
    hostname: auth
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}


  gateway:
    build:
      context: ./pma252.gateway-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080